GET http://localhost:8080/?name=Joe&friend=Chendler
Accept: application/json

###
POST http://localhost:8080/
Content-Type: application/x-www-form-urlencoded

name = "Chendler" &
wife = "Monica"

###

